#
# Copyright 2022 National Instruments Corporation
#
# SPDX-License-Identifier: MIT
#
# RF Data Collection API Configuration
#
# Notes: 
# - Seqtype: The parameter values can be given in range (start, stop, step), list, or single.
#
# =================================================
# ============= general configuration =============
# =================================================
general_config:
  # Path to store captured rx data, type = str
  rx_recorded_data_path: "recorded-data"
  # Rx recorded data saving format, type = str, possible values (SigMF)
  rx_recorded_data_saving_format: "SigMF"
  # Number of snapshots from RX IQ data acquisition, type= int
  nrecords: 10
  # Tx USRPs execution mode: "parallel" or "sequential"
  # parallel: TX USRPs will transmit their related waveforms simultaneously (in parallel)",
  # sequential: TX USRPs will transmit their related waveforms one by one in sequential manner: Transmit wavefor1, record IQ data, Transmit waveform2, record...",
  # Note: If there are more than one RX USRP, they will run in parallel."
  txs_execution: "parallel"
  # wireless_link_parameter_map: Parameters pair is given via parameter map dictionary (e.g. RFWS parameter name vs. SigMF meta-data parameter name)
  wireless_link_parameter_map: "wireless_link_parameter_map.yaml"
  # Enable or disable console logging: "True" or "False"
  enable_console_logging: "True"
  # Author name, handle, email, and/or other ID like Amateur Call Sign. 
  author: Abdo Gaber
  # A text description of the SigMF Recording.
  description: "API Rx Only Test"
  # captured_data_file_name: user prefered name for rx captured data
  captured_data_file_name: "rx-waveform-td-rec-"
  # User Comment
  comment: "Using NI RF Data Recording API"
# ============================================
# =============== Transmitters   =============
# ============================================
transmitters_config:
#
common_transmitters_config:
  tx_clock_reference:   # Tx sync reference source (internal, external, gpsdo), type = str.
    SeqType: "list"
    Values: ["internal"]
  tx_radio_id:    # radio block to use (e.g., 0 or 1), type = in.
    SeqType: "list"
    Values: [0]
  tx_radio_chan:  # radio channel to use, type = int.
    SeqType: "list"
    Values: [0]
  tx_replay_id:   # replay block to use (e.g., 0 or 1), type = int.
    SeqType: "list"
    Values: [0]
  tx_replay_chan: # replay channel to use, type = int.
    SeqType: "list"
    Values: [0]
  tx_duc_chan:    # duc channel to use, type = int.
    SeqType: "list"
    Values: [0]
  tx_duc_id:    # duc id to use, type = int.
    SeqType: "list"
    Values: [0]
# ============================================
# ================== Receivers   =============
# ============================================
receivers_config:
  -
    RFmode: "Rx"    # Tx or Rx, type=str.
    # USRP type and IPaddress will be used to create Device args to use when connecting to the USRP.
    type: "x4xx"    # USRP type, for example: x4xx, type=str.
    IPaddress: "192.168.100.2" # IP address of USRP, type=str.
    Parameters:
      freq:         # RF target center frequency in Hz, type = float.
        SeqType: "range"
        Values: [3.6e+9,3.6e+9,100.0e+6]
      rate:         # rate of radio block, type = float.
        SeqType: "list"
        Values: [92.16e+6]
      bandwidth:  # For future use
        SeqType: "list"
        Values: [100.0e+6]
      rate_source:  # waveform_config: The rate will be read from the waveform config file.
      # ............................in case of multi TX, the maximum rate will be used.
      # ............ user_defined: The given rate by the user in this config file will be used.
        SeqType: "single"
        Values: "user_defined"
      gain:       # Gain for the RF chain in dB, type = float.
        SeqType: "list"
        Values: [20]
      channels:   # Rx Channel selection (X310: 0,1) or (X410: 0,1,2,3).
        SeqType: "list"
        Values: [0]
      antenna:    # RX antenna selection (TX/RX, RX2), type = str.
        SeqType: "list"
        Values: ["TX/RX"]
      clock_reference:  # Rx sync reference source (internal, external, gpsdo), type = str.
        SeqType: "list"
        Values: ["internal"]
      duration:   # Rx Time duration of IQ data acquisition, type=float.
        SeqType: "list"
        Values: [10.0e-3]
      channel_attenuation: # Expected channel attenuation in dB, type = float.
        SeqType: "single"
        Values: 33.0
  -
    RFmode: "Rx"    # Tx or Rx, type=str.
    # USRP type and IPaddress will be used to create Device args to use when connecting to the USRP.
    type: "x4xx"    # USRP type, for example: x4xx, type=str.
    IPaddress: "192.168.110.2" # IP address of USRP, type=str.
    Parameters:
      freq:         # RF target center frequency in Hz, type = float.
        SeqType: "range"
        Values: [3.62e+9,3.62e+9,100.0e+6]
      rate:         # rate of radio block, type = float.
        SeqType: "list"
        Values: [92.16e+6]
      bandwidth:  # For future use
        SeqType: "list"
        Values: [100.0e+6]
      rate_source:  # waveform_config: The rate will be read from the waveform config file.
      # ............................in case of multi TX, the maximum rate will be used.
      # ............ user_defined: The given rate by the user in this config file will be used.
        SeqType: "single"
        Values: "user_defined"
      gain:       # Gain for the RF chain in dB, type = float.
        SeqType: "list"
        Values: [20]
      channels:   # Rx Channel selection (X310: 0,1) or (X410: 0,1,2,3).
        SeqType: "list"
        Values: [0]
      antenna:    # RX antenna selection (TX/RX, RX2), type = str.
        SeqType: "list"
        Values: ["TX/RX"]
      clock_reference:  # Rx sync reference source (internal, external, gpsdo), type = str.
        SeqType: "list"
        Values: ["internal"]
      duration:   # Rx Time duration of IQ data acquisition, type=float.
        SeqType: "list"
        Values: [10.0e-3]
      channel_attenuation: # Expected channel attenuation in dB, type = float.
        SeqType: "single"
        Values: 33.0