# Parameters list of waveform configuration
standard: ""
frequency_range: ""
link_direction: ""
duplexing: ""
multiplexing: ""
multiple_access: ""
spreading: ""
bandwidth: 0.0
rate: 0.0
MCS: ""
modulation: ""
modulation_order: ""
code_rate: ""
subcarrier_spacing: ""
n_frames: ""
test_model: ""
carrier_CC_index: ""
ssb_config_set: ""
ssb_periodicity: ""
IEEE_MAC_frame_type: ""
IEEE_PSDU_length_bytes: ""